package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/bensabler/ff6-decompile/internal/game/hudfont"
	"github.com/bensabler/ff6-decompile/internal/graphics/tile2bpp"
	"github.com/bensabler/ff6-decompile/internal/rom"
)

// glyphMapPath is the tracked glyph table. It records addresses, characters,
// and per-tile hashes — never tile pixels, which are ROM-derived.
const glyphMapPath = "data/graphics/hud-font-glyphs.json"

func graphicsCmd(args []string, w io.Writer) error {
	const usage = "usage: ff6lab graphics glyphmap [-rom <path>]"
	if len(args) < 1 || args[0] != "glyphmap" {
		return fmt.Errorf("%s", usage)
	}
	var explicit string
	for i := 1; i < len(args); i++ {
		if (args[i] == "-rom" || args[i] == "--rom") && i+1 < len(args) {
			explicit = args[i+1]
			i++
		}
	}
	p, err := rom.ResolvePath(explicit)
	if err != nil {
		return err
	}
	r, err := rom.Load(p)
	if err != nil {
		return err
	}
	return writeGlyphMap(r, ".", w)
}

func writeGlyphMap(r *rom.ROM, root string, w io.Writer) error {
	glyphs, err := buildGlyphMap(r)
	if err != nil {
		return err
	}
	if err := hudfont.Validate(glyphs); err != nil {
		return fmt.Errorf("generated glyph table is inconsistent: %w", err)
	}

	doc := map[string]any{
		"schema_version": "1.0",
		"description": "Battle HUD font glyph table. Maps each fixed-width encoding byte to " +
			"its tile in the ROM-0016 block via the EXP-0049 relation VRAM tile = $100 + byte. " +
			"Generated by `ff6lab graphics glyphmap`; do not hand-edit. Tile pixels are " +
			"ROM-derived and are not tracked - each row carries the tile's SHA-256 instead.",
		"rom_revision":       r.SHA256(),
		"block_rom_file":     fmt.Sprintf("ROMFILE:0x%06X-0x%06X", hudfont.BlockROMFile, hudfont.BlockROMFile+hudfont.BlockTiles*hudfont.TileBytes-1),
		"block_rom_cpu":      fmt.Sprintf("ROMCPU:$%06X", hudfont.BlockROMFile+0xC00000),
		"relation":           "vram_tile = 0x100 + encoded_byte; rom_file_offset = 0x047FC0 + 16*encoded_byte; sheet_index = encoded_byte + 1",
		"evidence":           []string{"EXP-0049", "EXP-0023", "GFX-0001", "ROM-0016"},
		"glyph_count":        len(glyphs),
		"character_count":    countClass(glyphs, hudfont.Character),
		"blank_count":        countClass(glyphs, hudfont.Blank),
		"structural_count":   countClass(glyphs, hudfont.Structural),
		"unidentified_count": countClass(glyphs, hudfont.Unidentified),
		"glyphs":             glyphs,
	}

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(doc); err != nil {
		return err
	}

	out := filepath.Join(root, glyphMapPath)
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(w, "%s regenerated: %d glyphs (%d characters, %d blank, %d structural, %d unidentified)\n",
		glyphMapPath, len(glyphs),
		countClass(glyphs, hudfont.Character), countClass(glyphs, hudfont.Blank),
		countClass(glyphs, hudfont.Structural), countClass(glyphs, hudfont.Unidentified))
	return nil
}

// buildGlyphMap decodes every glyph tile and classifies it. It reads the ROM
// but emits only addresses, characters, and hashes.
func buildGlyphMap(r *rom.ROM) ([]hudfont.Glyph, error) {
	glyphs := make([]hudfont.Glyph, 0, 256)
	for i := 0; i < 256; i++ {
		b := byte(i)
		off := hudfont.ROMFileOffset(b)
		src, err := r.Slice(off, hudfont.TileBytes)
		if err != nil {
			return nil, fmt.Errorf("glyph $%02X at ROMFILE:0x%06X: %w", b, off, err)
		}
		t, err := tile2bpp.Decode(src)
		if err != nil {
			return nil, fmt.Errorf("glyph $%02X: %w", b, err)
		}
		sum := sha256.Sum256(src)
		class, ch, conf := hudfont.Classify(b, tileIsBlank(t))
		glyphs = append(glyphs, hudfont.Glyph{
			EncodedByte:    b,
			VRAMTile:       hudfont.VRAMTile(b),
			SheetIndex:     hudfont.SheetIndex(b),
			ROMFileOffset:  off,
			Character:      ch,
			Classification: class,
			TileSHA256:     hex.EncodeToString(sum[:]),
			Confidence:     conf,
			Note:           hudfont.Note(b),
		})
	}
	return glyphs, nil
}

func tileIsBlank(t tile2bpp.Tile) bool {
	for y := range t {
		for x := range t[y] {
			if t[y][x] != 0 {
				return false
			}
		}
	}
	return true
}

func countClass(glyphs []hudfont.Glyph, c hudfont.Classification) int {
	n := 0
	for _, g := range glyphs {
		if g.Classification == c {
			n++
		}
	}
	return n
}
