package census

import (
	"fmt"
	"sort"
	"strings"
)

// DomainCoverage is one dashboard row: entry counts at ladder
// thresholds within a domain.
type DomainCoverage struct {
	Domain          string
	Registered      int
	Located         int // reconstruction >= LOCATED
	Decoded         int // >= FORMAT_DECODED
	Extracted       int // >= EXTRACTED_PARTIAL
	Implemented     int // >= IMPLEMENTED_PARTIAL
	RuntimeVerified int // runtime >= NORMAL_PATH_VERIFIED
}

// Summary computes per-domain coverage (all taxonomy domains, even
// empty ones — an empty row is a visible gap, not a hidden one).
func Summary(c Census) []DomainCoverage {
	byDomain := map[string]*DomainCoverage{}
	for _, d := range Domains {
		byDomain[d] = &DomainCoverage{Domain: d}
	}
	for _, e := range c.Entries {
		d, ok := byDomain[e.Domain]
		if !ok {
			continue // invalid domains reported by Validate
		}
		d.Registered++
		if AtLeast(ReconstructionLadder, e.ReconstructionStatus, "LOCATED") {
			d.Located++
		}
		if AtLeast(ReconstructionLadder, e.ReconstructionStatus, "FORMAT_DECODED") {
			d.Decoded++
		}
		if AtLeast(ReconstructionLadder, e.ReconstructionStatus, "EXTRACTED_PARTIAL") {
			d.Extracted++
		}
		if AtLeast(ReconstructionLadder, e.ReconstructionStatus, "IMPLEMENTED_PARTIAL") {
			d.Implemented++
		}
		if AtLeast(RuntimeLadder, e.RuntimeStatus, "NORMAL_PATH_VERIFIED") {
			d.RuntimeVerified++
		}
	}
	out := make([]DomainCoverage, 0, len(Domains))
	for _, d := range Domains {
		out = append(out, *byDomain[d])
	}
	return out
}

// Gap is an unowned ROM span.
type Gap struct {
	Start, Size int
}

// RomStats aggregates ledger accounting against the ROM size.
type RomStats struct {
	RomSize        int
	KnownBytes     int // status "known" regions (deduplicated)
	CandidateBytes int // bytes covered only by candidates
	CodeBytes      int // known CODE bytes
	DataBytes      int // known non-CODE bytes
	Gaps           []Gap
}

// Analyze computes coverage bytes and the unknown-gap list. Overlaps
// are counted once; candidate bytes exclude spans already known.
func Analyze(r Regions) RomStats {
	st := RomStats{RomSize: r.RomSize}
	type span struct{ start, end int }
	var known, cand []span
	for _, g := range r.Regions {
		s := span{g.Start, g.Start + g.Size}
		if g.Status == "known" {
			known = append(known, s)
			if g.Classification == "CODE" {
				st.CodeBytes += g.Size
			} else {
				st.DataBytes += g.Size
			}
		} else {
			cand = append(cand, s)
		}
	}
	merge := func(spans []span) []span {
		if len(spans) == 0 {
			return nil
		}
		sort.Slice(spans, func(i, j int) bool { return spans[i].start < spans[j].start })
		out := []span{spans[0]}
		for _, s := range spans[1:] {
			last := &out[len(out)-1]
			if s.start <= last.end {
				if s.end > last.end {
					last.end = s.end
				}
			} else {
				out = append(out, s)
			}
		}
		return out
	}
	km := merge(known)
	for _, s := range km {
		st.KnownBytes += s.end - s.start
	}
	// candidate bytes outside known spans
	for _, s := range merge(cand) {
		covered := 0
		for _, k := range km {
			lo, hi := max(s.start, k.start), min(s.end, k.end)
			if hi > lo {
				covered += hi - lo
			}
		}
		st.CandidateBytes += (s.end - s.start) - covered
	}
	// gaps relative to known+candidate coverage
	all := merge(append(append([]span(nil), known...), cand...))
	pos := 0
	for _, s := range all {
		if s.start > pos {
			st.Gaps = append(st.Gaps, Gap{pos, s.start - pos})
		}
		if s.end > pos {
			pos = s.end
		}
	}
	if pos < r.RomSize {
		st.Gaps = append(st.Gaps, Gap{pos, r.RomSize - pos})
	}
	return st
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

const generatedNote = "<!-- generated by `ff6lab census sync`; do not edit by hand -->\n\n"

// GenerateCensusIndex renders indexes/CONTENT_CENSUS.md.
func GenerateCensusIndex(c Census) string {
	var b strings.Builder
	b.WriteString("# Content Census\n\n")
	b.WriteString(generatedNote)
	b.WriteString(fmt.Sprintf("%d entries. Statuses per docs/research/CONTENT_TAXONOMY.md; entries live in manifests/content-census.json.\n\n", len(c.Entries)))
	b.WriteString("| ID | Domain | Category | Name | Reconstruction | Runtime | Confidence |\n|---|---|---|---|---|---|---|\n")
	entries := append([]Entry(nil), c.Entries...)
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })
	for _, e := range entries {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n",
			e.ID, e.Domain, e.Category, e.Name, e.ReconstructionStatus, e.RuntimeStatus, e.Confidence)
	}
	return b.String()
}

// GenerateRegionIndex renders indexes/ROM_REGIONS.md.
func GenerateRegionIndex(r Regions) string {
	st := Analyze(r)
	var b strings.Builder
	b.WriteString("# ROM Regions\n\n")
	b.WriteString(generatedNote)
	fmt.Fprintf(&b, "ROM: %d bytes, SHA-256 `%s`.\n", r.RomSize, r.RomSHA256)
	fmt.Fprintf(&b, "Known: %d bytes (%.2f%%) — %d code, %d data. Candidate-only: %d bytes. Unknown: %d bytes (%.2f%%) in %d gaps.\n\n",
		st.KnownBytes, pct(st.KnownBytes, r.RomSize), st.CodeBytes, st.DataBytes,
		st.CandidateBytes, unknownBytes(st), pct(unknownBytes(st), r.RomSize), len(st.Gaps))
	b.WriteString("| ID | ROMFILE span | ROMCPU | Class | Size | Status | Confidence | Owner |\n|---|---|---|---|---|---|---|---|\n")
	regions := append([]Region(nil), r.Regions...)
	sort.Slice(regions, func(i, j int) bool { return regions[i].Start < regions[j].Start })
	for _, g := range regions {
		fmt.Fprintf(&b, "| %s | 0x%06X-0x%06X | %s | %s | %d | %s | %s | %s |\n",
			g.ID, g.Start, g.Start+g.Size-1, g.Bank, g.Classification, g.Size, g.Status, g.Confidence, g.Owner)
	}
	return b.String()
}

func unknownBytes(st RomStats) int {
	total := 0
	for _, g := range st.Gaps {
		total += g.Size
	}
	return total
}

func pct(n, d int) float64 {
	if d == 0 {
		return 0
	}
	return float64(n) * 100 / float64(d)
}

// GenerateCoverageDashboard renders dashboards/COVERAGE.md.
func GenerateCoverageDashboard(c Census, r Regions) string {
	sum := Summary(c)
	st := Analyze(r)
	var b strings.Builder
	b.WriteString("# Coverage\n\n")
	b.WriteString(generatedNote)
	b.WriteString("Breadth without pretense: counts are census entries at or above each threshold (see docs/research/CONTENT_TAXONOMY.md). An empty domain row is an unregistered domain, not a finished one.\n\n")
	b.WriteString("| Domain | Registered | Located | Decoded | Extracted | Implemented | Runtime verified |\n|---|---|---|---|---|---|---|\n")
	for _, d := range sum {
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %d | %d |\n",
			d.Domain, d.Registered, d.Located, d.Decoded, d.Extracted, d.Implemented, d.RuntimeVerified)
	}
	b.WriteString("\n## ROM accounting\n\n")
	fmt.Fprintf(&b, "- Known: %d of %d bytes (%.2f%%) — code %d bytes (%.2f%%), data %d bytes (%.2f%%).\n",
		st.KnownBytes, st.RomSize, pct(st.KnownBytes, st.RomSize),
		st.CodeBytes, pct(st.CodeBytes, st.RomSize), st.DataBytes, pct(st.DataBytes, st.RomSize))
	fmt.Fprintf(&b, "- Candidate-only: %d bytes.\n", st.CandidateBytes)
	fmt.Fprintf(&b, "- **Unknown: %d bytes (%.2f%%)** across %d gaps.\n", unknownBytes(st), pct(unknownBytes(st), st.RomSize), len(st.Gaps))
	b.WriteString("\n## Census health\n\n")
	var unresolved, observedOnly, runtimeOnly, staticOnly int
	for _, e := range c.Entries {
		if len(e.UnknownFields) > 0 {
			unresolved++
		}
		if !AtLeast(ReconstructionLadder, e.ReconstructionStatus, "LOCATED") {
			observedOnly++
		}
		if AtLeast(RuntimeLadder, e.RuntimeStatus, "ENCOUNTERED") &&
			!AtLeast(ReconstructionLadder, e.ReconstructionStatus, "CANDIDATE_LOCATION") {
			runtimeOnly++
		}
		if AtLeast(ReconstructionLadder, e.ReconstructionStatus, "LOCATED") &&
			e.RuntimeStatus == "NOT_ENCOUNTERED" {
			staticOnly++
		}
	}
	fmt.Fprintf(&b, "- Entries with unresolved fields/formats: %d.\n", unresolved)
	fmt.Fprintf(&b, "- Observed but not yet located (breadth backlog): %d.\n", observedOnly)
	fmt.Fprintf(&b, "- Runtime-only findings (seen live, no location): %d.\n", runtimeOnly)
	fmt.Fprintf(&b, "- Static-only findings (located, never exercised live): %d.\n", staticOnly)
	b.WriteString("\n## Open breadth targets (next_action of unlocated entries)\n\n")
	entries := append([]Entry(nil), c.Entries...)
	sort.Slice(entries, func(i, j int) bool { return entries[i].ID < entries[j].ID })
	listed := 0
	for _, e := range entries {
		if !AtLeast(ReconstructionLadder, e.ReconstructionStatus, "LOCATED") {
			fmt.Fprintf(&b, "- **%s** (%s): %s\n", e.ID, e.Name, e.NextAction)
			listed++
		}
	}
	if listed == 0 {
		b.WriteString("- none — every registered entry is at least LOCATED.\n")
	}
	return b.String()
}

// TopGaps returns the n largest unknown spans.
func TopGaps(st RomStats, n int) []Gap {
	gaps := append([]Gap(nil), st.Gaps...)
	sort.Slice(gaps, func(i, j int) bool { return gaps[i].Size > gaps[j].Size })
	if len(gaps) > n {
		gaps = gaps[:n]
	}
	return gaps
}
